import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { paddingBottom: 32 },

  headerSection: {

    paddingHorizontal: 20,
    paddingBottom: 8,
    backgroundColor: "transparent",
  },
  greetingRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  greetingEmoji: { fontSize: 28, marginBottom: 4 },
  greetingText: { fontSize: 30, fontWeight: "900", lineHeight: 36 },
  greetingSubtext: { fontSize: 14, fontWeight: "500", marginTop: 4 },
  profileBtn: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 32,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },

  bigStatCard: {
    marginHorizontal: 20,
    marginTop: 16,
    borderRadius: 24,
    padding: 24,
    overflow: "hidden",
    shadowColor: "#4876EC",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 8,
  },
  bigStatContent: { flexDirection: "row", alignItems: "center" },
  bigStatLeft: { flex: 1, alignItems: "center", gap: 4 },
  streakTapArea: {
    borderRadius: 16,
    padding: 8,
    marginLeft: -8,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  tapHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    marginTop: 6,
  },
  tapHintText: {
    fontSize: 10,
    color: "rgba(255,255,255,0.65)",
    fontWeight: "600",
  },
  bigStatRight: { flex: 1, alignItems: "center", gap: 6 },
  bigStatDivider: {
    width: 1,
    height: 64,
    backgroundColor: "rgba(255,255,255,0.25)",
    marginHorizontal: 16,
  },
  streakBadge: { flexDirection: "row", alignItems: "center", gap: 4 },
  streakFire: { fontSize: 28 },
  streakNumber: { fontSize: 40, fontWeight: "900", color: "#fff" },
  bigStatLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "rgba(255,255,255,0.9)",
  },
  bigStatSublabel: {
    fontSize: 11,
    fontWeight: "500",
    color: "rgba(255,255,255,0.65)",
  },
  weekDots: { flexDirection: "row", gap: 6, alignItems: "flex-end" },
  weekDotCol: { alignItems: "center", gap: 4 },
  weekDot: { width: 10, height: 10, borderRadius: 5 },
  weekDayLabel: {
    fontSize: 9,
    color: "rgba(255,255,255,0.6)",
    fontWeight: "600",
  },

  miniStatsRow: {
    flexDirection: "row",
    paddingHorizontal: 20,
    marginTop: 12,
    gap: 10,
  },
  miniStatCard: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },

  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginTop: 28,
    marginBottom: 14,
  },
  sectionTitle: { fontSize: 20, fontWeight: "800" },
  seeAll: { fontSize: 14, fontWeight: "700" },

  recentList: { paddingHorizontal: 20, gap: 10 },
  recentCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 18,
    padding: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  recentIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  recentInfo: { flex: 1 },
  recentTitle: { fontSize: 15, fontWeight: "700", marginBottom: 2 },
  recentMeta: { fontSize: 13, fontWeight: "500" },
  recentCheckBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },

  workoutCardScroll: { paddingHorizontal: 20, gap: 12, paddingRight: 20 },
  workoutCard: {
    width: 156,
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  workoutCardAccent: { height: 4, width: "100%" },
  workoutCardBody: { padding: 14, gap: 8 },
  workoutCardIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  workoutCardTitle: { fontSize: 14, fontWeight: "700", lineHeight: 18 },
  workoutCardMeta: { fontSize: 12, fontWeight: "500" },
  workoutCardFooter: {
    borderTopWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  workoutCardStart: { fontSize: 13, fontWeight: "700" },

  emptyState: {
    alignItems: "center",
    paddingTop: 48,
    paddingHorizontal: 32,
    gap: 12,
  },
  emptyTitle: { fontSize: 22, fontWeight: "800" },
  emptySub: { fontSize: 15, textAlign: "center", lineHeight: 22 },
  emptyBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 20,
  },
  emptyBtnText: { color: "#fff", fontSize: 16, fontWeight: "700" },
});

export const noRecoStyles = StyleSheet.create({
  card: {
    marginHorizontal: 20,
    marginTop: 16,
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  icon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  title: { fontSize: 15, fontWeight: "700", marginBottom: 4 },
  sub: { fontSize: 13, lineHeight: 18 },
});
